version: '3.8'

services:
  renovate-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      # GitHub Authentication (choose one approach)
      # Production (GitHub App)
      - GITHUB_APP_ID=${GITHUB_APP_ID:-0}
      - GITHUB_APP_PRIVATE_KEY_PATH=/app/private-key.pem
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

      # Development (Personal Access Token)
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}

      # Required Configuration
      - GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION}

      # Optional Configuration
      - GITHUB_REPOSITORY_ALLOWLIST=${GITHUB_REPOSITORY_ALLOWLIST}
      - GITHUB_TEST_REPOSITORIES=${GITHUB_TEST_REPOSITORIES}

      # Application Configuration
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HOST=0.0.0.0
      - PORT=8000

      # Dependency Fixing Configuration
      - ENABLE_DEPENDENCY_FIXING=${ENABLE_DEPENDENCY_FIXING:-true}
      - SUPPORTED_LANGUAGES=${SUPPORTED_LANGUAGES:-python,typescript,go}
      - CLONE_TIMEOUT=${CLONE_TIMEOUT:-300}
      - DEPENDENCY_UPDATE_TIMEOUT=${DEPENDENCY_UPDATE_TIMEOUT:-600}

      # Dashboard Configuration
      - DASHBOARD_CREATION_MODE=${DASHBOARD_CREATION_MODE:-renovate-only}
    volumes:
      # Optional: GitHub App private key (for production)
      - ./config/private-key.pem:/app/private-key.pem:ro
      # Optional: Logs directory
      - ./logs:/app/logs
    networks:
      - renovate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  renovate-network:
    driver: bridge
