name: Pre-merge Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry show

      - name: Install pre-commit hooks
        run: |
          poetry run pre-commit install --install-hooks

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files --verbose --show-diff-on-failure
        timeout-minutes: 5
        env:
          SKIP: pytest

  test:
    name: Run Tests
    uses: ./.github/workflows/test-suite.yml
    with:
      python-versions: '["3.12", "3.13"]'  # Full matrix for pre-merge
      run-import-tests: true
      run-config-tests: true
      run-startup-tests: true
    secrets: inherit
